import { PRODUCT_QUERY } from "@/lib/query";
import Head from "next/head";
import Link from "next/link";
import { useQuery } from "urql";
import Product from "@/components/Product";
import { Gallery } from "@/styles/product/Gallery";
import { client } from "./_app";

export default function Home({ data }) {
  // FETCH PRODUCTS
  // const [result] = useQuery({ query: PRODUCT_QUERY });
  // const { data, fetching, error } = result;
  // const products = data?.products?.data;

  // console.log(data);

  // // LOADING
  // if (fetching) {
  //   return <p>Loading...</p>;
  // }
  // // ERROR
  // if (error) {
  //   return <p>Oh no ... {error.message}</p>;
  // }
  return (
    <>
      <Head>
        <title>Clothes</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <Gallery>
          {data.products.data.map((product) => (
            <Product product={product} key={product.attributes.slug} />
          ))}
        </Gallery>
      </main>
    </>
  );
}

export async function getServerSideProps() {
  const { data } = await client.query(PRODUCT_QUERY).toPromise();

  return {
    props: {
      data,
    },
  };
}
